# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMART_FARM_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SMART_FARM(object):
    def setupUi(self, SMART_FARM):
        SMART_FARM.setObjectName("SMART_FARM")
        SMART_FARM.resize(939, 545)
        self.centralwidget = QtWidgets.QWidget(SMART_FARM)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.LED1_1BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED1_1BUTTON.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.LED1_1BUTTON.setObjectName("LED1_1BUTTON")
        self.LED1_2BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED1_2BUTTON.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.LED1_2BUTTON.setObjectName("LED1_2BUTTON")
        self.LED1_3BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED1_3BUTTON.setGeometry(QtCore.QRect(70, 140, 75, 23))
        self.LED1_3BUTTON.setObjectName("LED1_3BUTTON")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(210, 130, 51, 51))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.LED2_3BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED2_3BUTTON.setGeometry(QtCore.QRect(270, 140, 75, 23))
        self.LED2_3BUTTON.setObjectName("LED2_3BUTTON")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(210, 10, 51, 51))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.LED2_1BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED2_1BUTTON.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.LED2_1BUTTON.setObjectName("LED2_1BUTTON")
        self.LED2_2BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED2_2BUTTON.setGeometry(QtCore.QRect(270, 80, 75, 23))
        self.LED2_2BUTTON.setObjectName("LED2_2BUTTON")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_6.setGeometry(QtCore.QRect(210, 70, 51, 51))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(410, 130, 51, 51))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.LED3_3BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED3_3BUTTON.setGeometry(QtCore.QRect(470, 140, 75, 23))
        self.LED3_3BUTTON.setObjectName("LED3_3BUTTON")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(410, 10, 51, 51))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.LED3_1BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED3_1BUTTON.setGeometry(QtCore.QRect(470, 20, 75, 23))
        self.LED3_1BUTTON.setObjectName("LED3_1BUTTON")
        self.LED3_2BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED3_2BUTTON.setGeometry(QtCore.QRect(470, 80, 75, 23))
        self.LED3_2BUTTON.setObjectName("LED3_2BUTTON")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(410, 70, 51, 51))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.TEMP1 = QtWidgets.QProgressBar(self.centralwidget)
        self.TEMP1.setGeometry(QtCore.QRect(10, 190, 141, 23))
        self.TEMP1.setProperty("value", 24)
        self.TEMP1.setObjectName("TEMP1")
        self.HUMID1 = QtWidgets.QProgressBar(self.centralwidget)
        self.HUMID1.setGeometry(QtCore.QRect(10, 230, 141, 23))
        self.HUMID1.setProperty("value", 24)
        self.HUMID1.setObjectName("HUMID1")
        self.LIGHT1 = QtWidgets.QProgressBar(self.centralwidget)
        self.LIGHT1.setGeometry(QtCore.QRect(10, 270, 141, 23))
        self.LIGHT1.setProperty("value", 24)
        self.LIGHT1.setObjectName("LIGHT1")
        self.HUMID2 = QtWidgets.QProgressBar(self.centralwidget)
        self.HUMID2.setGeometry(QtCore.QRect(210, 230, 141, 23))
        self.HUMID2.setProperty("value", 24)
        self.HUMID2.setObjectName("HUMID2")
        self.TEMP2 = QtWidgets.QProgressBar(self.centralwidget)
        self.TEMP2.setGeometry(QtCore.QRect(210, 190, 141, 23))
        self.TEMP2.setProperty("value", 24)
        self.TEMP2.setObjectName("TEMP2")
        self.LIGHT2 = QtWidgets.QProgressBar(self.centralwidget)
        self.LIGHT2.setGeometry(QtCore.QRect(210, 270, 141, 23))
        self.LIGHT2.setProperty("value", 24)
        self.LIGHT2.setObjectName("LIGHT2")
        self.HUMID3 = QtWidgets.QProgressBar(self.centralwidget)
        self.HUMID3.setGeometry(QtCore.QRect(410, 230, 141, 23))
        self.HUMID3.setProperty("value", 24)
        self.HUMID3.setObjectName("HUMID3")
        self.TEMP3 = QtWidgets.QProgressBar(self.centralwidget)
        self.TEMP3.setGeometry(QtCore.QRect(410, 190, 141, 23))
        self.TEMP3.setProperty("value", 24)
        self.TEMP3.setObjectName("TEMP3")
        self.LIGHT3 = QtWidgets.QProgressBar(self.centralwidget)
        self.LIGHT3.setGeometry(QtCore.QRect(410, 270, 141, 23))
        self.LIGHT3.setProperty("value", 24)
        self.LIGHT3.setObjectName("LIGHT3")
        self.FARM1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FARM1.setGeometry(QtCore.QRect(10, 320, 141, 151))
        self.FARM1.setAutoFillBackground(False)
        self.FARM1.setStyleSheet("QGraphicsView#FARM1{\n"
"    background : rgb(105, 211, 0);\n"
"}")
        self.FARM1.setObjectName("FARM1")
        self.FARM2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FARM2.setGeometry(QtCore.QRect(210, 320, 141, 151))
        self.FARM2.setAutoFillBackground(False)
        self.FARM2.setStyleSheet("QGraphicsView#FARM2{\n"
"    background : rgb(105, 211, 0);\n"
"}")
        self.FARM2.setObjectName("FARM2")
        self.FARM3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FARM3.setGeometry(QtCore.QRect(410, 320, 141, 151))
        self.FARM3.setAutoFillBackground(False)
        self.FARM3.setStyleSheet("QGraphicsView#FARM3{\n"
"    background : rgb(105, 211, 0);\n"
"}")
        self.FARM3.setObjectName("FARM3")
        self.NAME1 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME1.setGeometry(QtCore.QRect(10, 480, 141, 21))
        self.NAME1.setObjectName("NAME1")
        self.NAME2 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME2.setGeometry(QtCore.QRect(210, 480, 141, 21))
        self.NAME2.setObjectName("NAME2")
        self.NAME3 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME3.setGeometry(QtCore.QRect(410, 480, 141, 21))
        self.NAME3.setObjectName("NAME3")
        self.menu = QtWidgets.QGraphicsView(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(580, 0, 341, 501))
        self.menu.setStyleSheet("QGraphicsView#menu{\n"
"background: rgb(0, 132, 0);\n"
"}")
        self.menu.setObjectName("menu")
        self.doorimage = QtWidgets.QGraphicsView(self.centralwidget)
        self.doorimage.setGeometry(QtCore.QRect(610, 20, 101, 101))
        self.doorimage.setObjectName("doorimage")
        self.door_status = QtWidgets.QLabel(self.centralwidget)
        self.door_status.setGeometry(QtCore.QRect(730, 50, 111, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.door_status.setFont(font)
        self.door_status.setObjectName("door_status")
        self.NAME1_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME1_1.setGeometry(QtCore.QRect(600, 180, 113, 31))
        self.NAME1_1.setReadOnly(True)
        self.NAME1_1.setObjectName("NAME1_1")
        self.NAME2_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME2_1.setEnabled(True)
        self.NAME2_1.setGeometry(QtCore.QRect(600, 280, 113, 31))
        self.NAME2_1.setReadOnly(True)
        self.NAME2_1.setObjectName("NAME2_1")
        self.NAME3_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME3_1.setGeometry(QtCore.QRect(600, 390, 113, 31))
        self.NAME3_1.setReadOnly(True)
        self.NAME3_1.setObjectName("NAME3_1")
        self.WIND1 = QtWidgets.QPushButton(self.centralwidget)
        self.WIND1.setGeometry(QtCore.QRect(720, 220, 75, 41))
        self.WIND1.setObjectName("WIND1")
        self.OPEN1 = QtWidgets.QPushButton(self.centralwidget)
        self.OPEN1.setGeometry(QtCore.QRect(820, 220, 75, 41))
        self.OPEN1.setObjectName("OPEN1")
        self.WIND2 = QtWidgets.QPushButton(self.centralwidget)
        self.WIND2.setGeometry(QtCore.QRect(720, 320, 75, 41))
        self.WIND2.setObjectName("WIND2")
        self.OPEN2 = QtWidgets.QPushButton(self.centralwidget)
        self.OPEN2.setGeometry(QtCore.QRect(820, 320, 75, 41))
        self.OPEN2.setObjectName("OPEN2")
        self.WIND3 = QtWidgets.QPushButton(self.centralwidget)
        self.WIND3.setGeometry(QtCore.QRect(720, 440, 75, 41))
        self.WIND3.setObjectName("WIND3")
        self.OPEN3 = QtWidgets.QPushButton(self.centralwidget)
        self.OPEN3.setGeometry(QtCore.QRect(820, 440, 75, 41))
        self.OPEN3.setObjectName("OPEN3")
        SMART_FARM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SMART_FARM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 21))
        self.menubar.setObjectName("menubar")
        SMART_FARM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SMART_FARM)
        self.statusbar.setObjectName("statusbar")
        SMART_FARM.setStatusBar(self.statusbar)

        self.retranslateUi(SMART_FARM)
        QtCore.QMetaObject.connectSlotsByName(SMART_FARM)

    def retranslateUi(self, SMART_FARM):
        _translate = QtCore.QCoreApplication.translate
        SMART_FARM.setWindowTitle(_translate("SMART_FARM", "SMARTFARM"))
        self.LED1_1BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED1_2BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED1_3BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED2_3BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED2_1BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED2_2BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED3_3BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED3_1BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.LED3_2BUTTON.setText(_translate("SMART_FARM", "PushButton"))
        self.TEMP1.setFormat(_translate("SMART_FARM", "%pC"))
        self.LIGHT1.setFormat(_translate("SMART_FARM", "%p"))
        self.TEMP2.setFormat(_translate("SMART_FARM", "%pC"))
        self.LIGHT2.setFormat(_translate("SMART_FARM", "%p"))
        self.TEMP3.setFormat(_translate("SMART_FARM", "%pC"))
        self.LIGHT3.setFormat(_translate("SMART_FARM", "%p"))
        self.door_status.setText(_translate("SMART_FARM", "열림"))
        self.WIND1.setText(_translate("SMART_FARM", "PushButton"))
        self.OPEN1.setText(_translate("SMART_FARM", "PushButton"))
        self.WIND2.setText(_translate("SMART_FARM", "PushButton"))
        self.OPEN2.setText(_translate("SMART_FARM", "PushButton"))
        self.WIND3.setText(_translate("SMART_FARM", "PushButton"))
        self.OPEN3.setText(_translate("SMART_FARM", "PushButton"))

#import bulb_on_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SMART_FARM = QtWidgets.QMainWindow()
    ui = Ui_SMART_FARM()
    ui.setupUi(SMART_FARM)
    SMART_FARM.show()
    sys.exit(app.exec_())

