# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMART_FARM_TEST_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SMART_FARM(object):
    def setupUi(self, SMART_FARM):
        SMART_FARM.setObjectName("SMART_FARM")
        SMART_FARM.resize(369, 384)
        self.centralwidget = QtWidgets.QWidget(SMART_FARM)
        self.centralwidget.setStyleSheet("background: url(:/bg/image/bg.png)")
        self.centralwidget.setObjectName("centralwidget")
        self.LED1BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED1BUTTON.setGeometry(QtCore.QRect(80, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.LED1BUTTON.setFont(font)
        self.LED1BUTTON.setStyleSheet("QPushButton#LED1BUTTON{\n"
"background: white;\n"
"}")
        self.LED1BUTTON.setObjectName("LED1BUTTON")
        self.LED2BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED2BUTTON.setGeometry(QtCore.QRect(80, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.LED2BUTTON.setFont(font)
        self.LED2BUTTON.setStyleSheet("QPushButton#LED2BUTTON{\n"
"background: white;\n"
"}")
        self.LED2BUTTON.setObjectName("LED2BUTTON")
        self.LED3BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.LED3BUTTON.setGeometry(QtCore.QRect(80, 180, 75, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.LED3BUTTON.setFont(font)
        self.LED3BUTTON.setStyleSheet("QPushButton#LED3BUTTON{\n"
"background: white;\n"
"}")
        self.LED3BUTTON.setObjectName("LED3BUTTON")
        self.TEMP1 = QtWidgets.QProgressBar(self.centralwidget)
        self.TEMP1.setGeometry(QtCore.QRect(210, 140, 141, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.TEMP1.setFont(font)
        self.TEMP1.setProperty("value", 24)
        self.TEMP1.setObjectName("TEMP1")
        self.HUMID1 = QtWidgets.QProgressBar(self.centralwidget)
        self.HUMID1.setGeometry(QtCore.QRect(210, 190, 141, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.HUMID1.setFont(font)
        self.HUMID1.setProperty("value", 24)
        self.HUMID1.setObjectName("HUMID1")
        self.LIGHT1 = QtWidgets.QProgressBar(self.centralwidget)
        self.LIGHT1.setGeometry(QtCore.QRect(210, 240, 141, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.LIGHT1.setFont(font)
        self.LIGHT1.setProperty("value", 24)
        self.LIGHT1.setObjectName("LIGHT1")
        self.WINDBUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.WINDBUTTON.setGeometry(QtCore.QRect(10, 300, 81, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.WINDBUTTON.setFont(font)
        self.WINDBUTTON.setStyleSheet("QPushButton#WINDBUTTON{\n"
"background:white;\n"
"}")
        self.WINDBUTTON.setObjectName("WINDBUTTON")
        self.WINDOWBUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.WINDOWBUTTON.setGeometry(QtCore.QRect(110, 300, 81, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.WINDOWBUTTON.setFont(font)
        self.WINDOWBUTTON.setStyleSheet("QPushButton#WINDOWBUTTON{\n"
"background: white;\n"
"}")
        self.WINDOWBUTTON.setObjectName("WINDOWBUTTON")
        self.WATER1 = QtWidgets.QProgressBar(self.centralwidget)
        self.WATER1.setGeometry(QtCore.QRect(210, 290, 141, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.WATER1.setFont(font)
        self.WATER1.setProperty("value", 24)
        self.WATER1.setObjectName("WATER1")
        self.bulbpicture1 = QtWidgets.QWidget(self.centralwidget)
        self.bulbpicture1.setGeometry(QtCore.QRect(30, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.bulbpicture1.setFont(font)
        self.bulbpicture1.setStyleSheet("background: url(:/bulb/image/idea (1).png)")
        self.bulbpicture1.setObjectName("bulbpicture1")
        self.bulbpicture2 = QtWidgets.QWidget(self.centralwidget)
        self.bulbpicture2.setGeometry(QtCore.QRect(30, 110, 41, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.bulbpicture2.setFont(font)
        self.bulbpicture2.setStyleSheet("background: url(:/bulb/image/idea (1).png)")
        self.bulbpicture2.setObjectName("bulbpicture2")
        self.bulbpicture3 = QtWidgets.QWidget(self.centralwidget)
        self.bulbpicture3.setGeometry(QtCore.QRect(30, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.bulbpicture3.setFont(font)
        self.bulbpicture3.setStyleSheet("background: url(:/bulb/image/idea (1).png)")
        self.bulbpicture3.setObjectName("bulbpicture3")
        self.windpicture = QtWidgets.QWidget(self.centralwidget)
        self.windpicture.setGeometry(QtCore.QRect(20, 230, 61, 61))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.windpicture.setFont(font)
        self.windpicture.setStyleSheet("background: url(:/wind/C:/Users/DSM2018/Downloads/breeze.png)")
        self.windpicture.setObjectName("windpicture")
        self.windowpicture = QtWidgets.QWidget(self.centralwidget)
        self.windowpicture.setGeometry(QtCore.QRect(120, 230, 61, 61))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.windowpicture.setFont(font)
        self.windowpicture.setStyleSheet("background:url(:/window/image/opened-window-door-of-glasses.png);")
        self.windowpicture.setObjectName("windowpicture")
        self.doorpicture = QtWidgets.QWidget(self.centralwidget)
        self.doorpicture.setGeometry(QtCore.QRect(190, 10, 81, 91))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.doorpicture.setFont(font)
        self.doorpicture.setStyleSheet("background:url(:/door/image/come-in.png)")
        self.doorpicture.setObjectName("doorpicture")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 10, 131, 22))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.DOORBUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.DOORBUTTON.setGeometry(QtCore.QRect(270, 20, 81, 71))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.DOORBUTTON.setFont(font)
        self.DOORBUTTON.setStyleSheet("QPushButton#DOORBUTTON{\n"
"background: white;\n"
"}")
        self.DOORBUTTON.setObjectName("DOORBUTTON")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(210, 120, 31, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.temp.setFont(font)
        self.temp.setObjectName("temp")
        self.humid = QtWidgets.QLabel(self.centralwidget)
        self.humid.setGeometry(QtCore.QRect(210, 170, 31, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.humid.setFont(font)
        self.humid.setObjectName("humid")
        self.light = QtWidgets.QLabel(self.centralwidget)
        self.light.setGeometry(QtCore.QRect(210, 220, 31, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.light.setFont(font)
        self.light.setObjectName("light")
        self.water = QtWidgets.QLabel(self.centralwidget)
        self.water.setGeometry(QtCore.QRect(210, 270, 31, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.water.setFont(font)
        self.water.setObjectName("water")
        SMART_FARM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SMART_FARM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 369, 21))
        self.menubar.setObjectName("menubar")
        SMART_FARM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SMART_FARM)
        self.statusbar.setObjectName("statusbar")
        SMART_FARM.setStatusBar(self.statusbar)

        self.retranslateUi(SMART_FARM)
        QtCore.QMetaObject.connectSlotsByName(SMART_FARM)

    def retranslateUi(self, SMART_FARM):
        _translate = QtCore.QCoreApplication.translate
        SMART_FARM.setWindowTitle(_translate("SMART_FARM", "SMARTFARM"))
        self.LED1BUTTON.setText(_translate("SMART_FARM", "OFF"))
        self.LED2BUTTON.setText(_translate("SMART_FARM", "OFF"))
        self.LED3BUTTON.setText(_translate("SMART_FARM", "OFF"))
        self.TEMP1.setFormat(_translate("SMART_FARM", "%pC"))
        self.LIGHT1.setFormat(_translate("SMART_FARM", "%pcd"))
        self.WINDBUTTON.setText(_translate("SMART_FARM", "OFF"))
        self.WINDOWBUTTON.setText(_translate("SMART_FARM", "OFF"))
        self.WATER1.setFormat(_translate("SMART_FARM", "%p"))
        self.comboBox.setItemText(0, _translate("SMART_FARM", "딸기"))
        self.comboBox.setItemText(1, _translate("SMART_FARM", "포도"))
        self.DOORBUTTON.setText(_translate("SMART_FARM", "CLOSE"))
        self.temp.setText(_translate("SMART_FARM", "온도"))
        self.humid.setText(_translate("SMART_FARM", "습도"))
        self.light.setText(_translate("SMART_FARM", "빛"))
        self.water.setText(_translate("SMART_FARM", "수분"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SMART_FARM = QtWidgets.QMainWindow()
    ui = Ui_SMART_FARM()
    ui.setupUi(SMART_FARM)
    SMART_FARM.show()
    sys.exit(app.exec_())

